const config = {
  repository: {
    name: 'cli-practice',
    iconExtractPath: 'turborepo-starter/packages/icons',
    baseBranchName: 'main',
    owner: 'ShinYoung-Kim',
  },
  commit: {
    message: 'feat(bezier-icons): update icons',
    author: {
      name: 'ShinYoung-Kim',
      email: 'lukey0515@gmail.com',
    },
  },
  pr: {
    title: 'feat(bezier-icons): update icons',
    body: 'Please check the changed part!\n---\nThis Pull Request was generated by bezier-figma-plugin.',
    labels: ['feat:icon'],
  },
};

export default config;
